# This is a basic workflow to help you get started with Actions

name: Screenshot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Screenshot
        uses: "lannonbr/puppeteer-screenshot-action@1.3.1"
        with:
          url: https://chatpic.org/r/nsfw/15min
      - name: push to branch
        run: |
          set -x
          git status
          git add .
          git checkout -b screenshots
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -m 'update screenshot'
          git push origin screenshots -f
